inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'

# １行に150文字まで許可
Metrics/LineLength:
  Max: 150

# キーワード引数以外も使用可
Airbnb/OptArgParameters:
  Enabled: false

# product_decoratorに定数を定義できるようにするため
Airbnb/ConstAssignedInWrongFile:
  Exclude:
    - 'app/models/spree/*'

# product_decoratorにメソッドを定義できるようにするため
Airbnb/ModuleMethodInWrongFile:
  Exclude:
    - 'app/models/spree/*'
